# --- Config ---
WIDTH = 800
HEIGHT = 600
ROAD_Y = HEIGHT // 2
ROAD_HEIGHT = 100
CAR_WIDTH = 60 
CAR_HEIGHT = 30
PEDESTRIAN_SIZE = 20
PEDESTRIAN_SPEED = 1
CAR_SPEED = 10
VERTICAL = 'vertical'
HORIZONTAL = 'horizontal'